version: '3'

services:

##################### Rails #####################
    workspace:
      build:
        context: ./workspace
        args:
          - RUBY_VERSION=${RUBY_VERSION}
        volumes:
          - ${RAILS_CODE_PATH}:/usr/src/rails
        depends_on:
          - mysql
          - postgres
          - redis
          - memcached

##################### MySQL #####################
    mysql:
      build:
        context: ./mysql

##################### Postgres #####################
    postgres:
      build:
        context: ./postgres

##################### Redis #####################
    redis:
      build:
        context: ./redis

##################### Memcached #####################
    memcached:
      build:
        context: ./memcached
