version: '3'

services:

##################### Rails #####################
    workspace:
      build:
        context: ./workspace
        args:
          - RUBY_VERSION=${RUBY_VERSION}
      volumes:
        - ${RAILS_CODE_PATH}:/usr/src/rails
      tty: true
      depends_on:
        - mysql
        - postgres
        - redis
        - memcached

##################### MySQL #####################
    mysql:
      image: mysql:${MYSQL_VERSION}
      command: --default-authentication-plugin=mysql_native_password
      restart: always
      volumes:
        - mysql:/var/lib/mysql
        - ./mysql/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
      ports:
        - "3306:3306"
        - "33060:33060"
      environment:
        - MYSQL_ROOT_PASSWORD=root
        - MYSQL_USER=rails
        - MYSQL_PASSWORD=rails

##################### Postgres #####################
    postgres:
      image: postgres:${POSTGRES_VERSION}
      restart: always
      volumes:
        - postgres:/var/lib/postgresql/data
      ports:
        - "5432:5432"
      environment:
        - POSTGRES_PASSWORD=root
        - POSTGRES_USER=rails

##################### Redis #####################
    redis:
      image: redis:${REDIS_VERSION}
      restart: always
      volumes:
        - redis:/data
      ports:
        - "6379:6379"

##################### Memcached #####################
    memcached:
      image: memcached:${MEMCACHED_VERSION}
      restart: always
      ports:
        - "11211:11211"

volumes:
  mysql:
    driver: local
  postgres:
    driver: local
  redis:
    driver: local
