version: '3'

services:

##################### Rails #####################
    workspace:
      build:
        context: ./workspace
        args:
          - RUBY_VERSION=${RUBY_VERSION}
        volumes:
          - .:/usr/src/app
        depends_on:
          - database

##################### MySQL #####################
    mysql:
      build:
        context: ./mysql

##################### Postgres #####################
    postgres:
      build:
        context: ./postgres

##################### Redis #####################
    redis:
      build:
        context: ./redis

##################### Memcached #####################
    memcached:
      build:
        context: ./memcached
